AllCops:
  Exclude:
    - 'spec/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Max: 120

FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

